services:
  simplegit:
    build: .
    ports:
      - "3000:3000"
      - "2222:2222"
    volumes:
      - ./repositories:/app/repositories
      - ./data:/app/data
      - ./ssh:/app/ssh
    environment:
      - SIMPLEGIT_PORT=3000
      - SIMPLEGIT_SSH_PORT=2222
      - SIMPLEGIT_JWT_SECRET=change-me-in-production
      - SIMPLEGIT_DOMAIN=localhost
      - SIMPLEGIT_MAX_FILE_SIZE=10485760
      - TS_SERVICE_URL=http://ts-worker:3001
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M
  ts-worker:
    build:
      context: ./services/ts-worker
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 64M

networks:
  backend:
    driver: bridge