version: "3.8"

services:
  simplegit:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./repositories:/app/repositories
    restart: unless-stopped

    # Optional: resource limits
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M