version: "3.8"

services:
  simplegit:
    build: .
    ports:
      - "3000:3000"
      - "2222:2222"
    volumes:
      - ./repositories:/app/repositories
      - ./data:/app/data
      - ./ssh:/app/ssh
    environment:
      - SIMPLEGIT_PORT=3000
      - SIMPLEGIT_SSH_PORT=2222
      - SIMPLEGIT_JWT_SECRET=change-me-in-production
      - SIMPLEGIT_DOMAIN=localhost
      - SIMPLEGIT_MAX_FILE_SIZE=10485760
      - TS_SERVICE_URL=http://localhost:3001
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 768M
        reservations:
          memory: 256M